### ISSUE TITLE
Compiling issue MACOSX. fatal error: sys/sysinfo.h

### ISSUE THREAD

**Issue by Chjulian** [ruanjue/wtdbg-1.2.8#3]
Hi. I am trying to compile in macOS Sierra 10.12.6
I keep getting an error message, do you have any idea how to solve it?

Some specs
x86_64-apple-darwin16.7.0
Apple LLVM version 9.0.0 (clang-900.0.37)
gcc (Homebrew) 7.2.0
command line tools are already installed
Xcode 9.0 Build version 9A235

```
$ make
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Tue Oct 10 13:45:10 CEST 2017" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o kbm-1.2.8 kbm.c -lm -lrt -lpthread
In file included from list.h:28:0,
                 from kbm.h:23,
                 from kbm.c:20:
mem_share.h:33:10: fatal error: sys/sysinfo.h: No such file or directory
 #include <sys/sysinfo.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [kbm-1.2.8] Error 1

$ make CC=clang
clang -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Tue Oct 10 13:45:16 CEST 2017" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o kbm-1.2.8 kbm.c -lm -lrt -lpthread
clang: warning: -O4 is equivalent to -O3 [-Wdeprecated]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
In file included from kbm.c:20:
In file included from ./kbm.h:23:
In file included from ./list.h:28:
./mem_share.h:33:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [kbm-1.2.8] Error 1
```

**Comment by ruanjue** [comment]
Please see the commit 3ac39d36834ed8827dfcb6bce44243c291e0cf7f

I haven't tested wtdbg in non-Linux OS, not sure whether it can be successfully compiled in MAC.
